mkdir a:\gp
copy c:\gp\latest a:\gp\
copy c:\gp\back.bat a:\gp\
copy c:\gp\accskel.c a:\gp\
copy c:\gp\appskel.c a:\gp\
copy c:\gp\ascii.h a:\gp\
copy c:\gp\basenam.c a:\gp\
copy c:\gp\bitrev.c a:\gp\
copy c:\gp\charq.h a:\gp\
copy c:\gp\cmeta.c a:\gp\
copy c:\gp\cmeta.h a:\gp\
copy c:\gp\cstd.cpy a:\gp\
copy c:\gp\ctype.c a:\gp\
copy c:\gp\ctype.h a:\gp\
copy c:\gp\dbentr.c a:\gp\
copy c:\gp\debug.h a:\gp\
copy c:\gp\genmain.c a:\gp\
copy c:\gp\getint.c a:\gp\
copy c:\gp\getline.c a:\gp\
copy c:\gp\getopt.c a:\gp\
copy c:\gp\getopt.h a:\gp\
copy c:\gp\getword.c a:\gp\
copy c:\gp\gplists.h a:\gp\
copy c:\gp\gpmain.c a:\gp\
copy c:\gp\gpmain.h a:\gp\
copy c:\gp\gptest.c a:\gp\
copy c:\gp\makefnm.c a:\gp\
copy c:\gp\mangle.c a:\gp\
copy c:\gp\mdump.c a:\gp\
copy c:\gp\newline.c a:\gp\
copy c:\gp\pagedefs.h a:\gp\
copy c:\gp\pageparm.h a:\gp\
copy c:\gp\prbits.c a:\gp\
copy c:\gp\rdcheck.c a:\gp\
copy c:\gp\rdline.c a:\gp\
copy c:\gp\setcq.c a:\gp\
copy c:\gp\setwq.c a:\gp\
copy c:\gp\stddefs.h a:\gp\
copy c:\gp\stdopen.c a:\gp\
copy c:\gp\testcq.c a:\gp\
copy c:\gp\testwq.c a:\gp\
copy c:\gp\tolower.c a:\gp\
copy c:\gp\toupper.c a:\gp\
copy c:\gp\wordq.h a:\gp\
df a:
