mkdir a:\ram
copy c:\ram\latest a:\ram\
copy c:\ram\back3.bat a:\ram\
copy c:\ram\scadv.c a:\ram\
copy c:\ram\scfield.c a:\ram\
copy c:\ram\scgoto.c a:\ram\
copy c:\ram\scinit.c a:\ram\
copy c:\ram\scope.c a:\ram\
copy c:\ram\scordsp.c a:\ram\
copy c:\ram\scread.c a:\ram\
copy c:\ram\scselbx.c a:\ram\
copy c:\ram\sctrak.c a:\ram\
copy c:\ram\scwrite.c a:\ram\
copy c:\ram\seccpy.c a:\ram\
copy c:\ram\sedisp.s a:\ram\
copy c:\ram\sedump.c a:\ram\
copy c:\ram\seexec.s a:\ram\
copy c:\ram\select.c a:\ram\
copy c:\ram\sendval.c a:\ram\
copy c:\ram\serintr.s a:\ram\
copy c:\ram\setgc.c a:\ram\
copy c:\ram\setpath.bat a:\ram\
copy c:\ram\setv2gi.c a:\ram\
copy c:\ram\setwq.c a:\ram\
copy c:\ram\showcfg.c a:\ram\
copy c:\ram\smscrl.c a:\ram\
copy c:\ram\sqdisp.c a:\ram\
copy c:\ram\sqdkey.c a:\ram\
copy c:\ram\sqexec.c a:\ram\
copy c:\ram\sqfield.c a:\ram\
copy c:\ram\sqread.c a:\ram\
copy c:\ram\sqscan.c a:\ram\
copy c:\ram\sqselbx.c a:\ram\
copy c:\ram\sqwrite.c a:\ram\
copy c:\ram\sreset.s a:\ram\
copy c:\ram\stcpos.c a:\ram\
copy c:\ram\stmproc.c a:\ram\
copy c:\ram\swinit.c a:\ram\
copy c:\ram\tdfield.c a:\ram\
copy c:\ram\tdselbx.c a:\ram\
copy c:\ram\tempo.c a:\ram\
copy c:\ram\timeint.s a:\ram\
copy c:\ram\tofpu.s a:\ram\
copy c:\ram\ttcpos.c a:\ram\
copy c:\ram\tundsp.c a:\ram\
copy c:\ram\ucslice.c a:\ram\
copy c:\ram\uslice.c a:\ram\
copy c:\ram\vtyper.c a:\ram\
copy c:\ram\wdfield.c a:\ram\
copy c:\ram\wdselbx.c a:\ram\
copy c:\ram\wheel.c a:\ram\
copy c:\ram\wscalc.c a:\ram\
copy c:\ram\wsdsp.c a:\ram\
df a:
