mkdir a:\ram
copy c:\ram\latest a:\ram\
copy c:\ram\back1.bat a:\ram\
copy c:\ram\addfpu.c a:\ram\
copy c:\ram\adfield.c a:\ram\
copy c:\ram\adselbx.c a:\ram\
copy c:\ram\arcram.bat a:\ram\
copy c:\ram\asgdsp.c a:\ram\
copy c:\ram\asgvce.c a:\ram\
copy c:\ram\barbadj.c a:\ram\
copy c:\ram\chgsef.c a:\ram\
copy c:\ram\chksec.c a:\ram\
copy c:\ram\cminit.c a:\ram\
copy c:\ram\ctcpos.c a:\ram\
copy c:\ram\curset.c a:\ram\
copy c:\ram\dbentr.c a:\ram\
copy c:\ram\dcopy.c a:\ram\
copy c:\ram\dec2fr.c a:\ram\
copy c:\ram\delnote.c a:\ram\
copy c:\ram\delpnts.c a:\ram\
copy c:\ram\dformat.c a:\ram\
copy c:\ram\dopatch.c a:\ram\
copy c:\ram\enterit.c a:\ram\
copy c:\ram\etaccn.c a:\ram\
copy c:\ram\etadep.c a:\ram\
copy c:\ram\etadyn.c a:\ram\
copy c:\ram\etagch.c a:\ram\
copy c:\ram\etagpt.c a:\ram\
copy c:\ram\etains.c a:\ram\
copy c:\ram\etaint.c a:\ram\
copy c:\ram\etaopt.c a:\ram\
copy c:\ram\etaprg.c a:\ram\
copy c:\ram\etarat.c a:\ram\
copy c:\ram\etatab.c a:\ram\
copy c:\ram\etatun.c a:\ram\
copy c:\ram\etavgr.c a:\ram\
copy c:\ram\etdyn.c a:\ram\
copy c:\ram\etiact.c a:\ram\
copy c:\ram\eticnf.c a:\ram\
copy c:\ram\etidin.c a:\ram\
copy c:\ram\etimlt.c a:\ram\
copy c:\ram\etinst.c a:\ram\
copy c:\ram\etioas.c a:\ram\
copy c:\ram\etiosc.c a:\ram\
copy c:\ram\etipnt.c a:\ram\
copy c:\ram\etires.c a:\ram\
copy c:\ram\etitim.c a:\ram\
copy c:\ram\etival.c a:\ram\
copy c:\ram\etivce.c a:\ram\
copy c:\ram\etiwsn.c a:\ram\
copy c:\ram\etloc.c a:\ram\
copy c:\ram\etmcfn.c a:\ram\
copy c:\ram\etrel.c a:\ram\
copy c:\ram\etres1.c a:\ram\
copy c:\ram\etscor.c a:\ram\
copy c:\ram\etsnbt.c a:\ram\
copy c:\ram\etstrn.c a:\ram\
copy c:\ram\ettpch.c a:\ram\
copy c:\ram\ettrns.c a:\ram\
copy c:\ram\etttab.c a:\ram\
copy c:\ram\ettval.c a:\ram\
copy c:\ram\etvel.c a:\ram\
copy c:\ram\etwavs.c a:\ram\
copy c:\ram\etwhar.c a:\ram\
copy c:\ram\etwhrv.c a:\ram\
copy c:\ram\etwoff.c a:\ram\
copy c:\ram\etwpnt.c a:\ram\
copy c:\ram\etwslt.c a:\ram\
copy c:\ram\etwvce.c a:\ram\
copy c:\ram\execins.s a:\ram\
copy c:\ram\execkey.s a:\ram\
copy c:\ram\fcnote.c a:\ram\
copy c:\ram\fpuint.s a:\ram\
copy c:\ram\frfind.c a:\ram\
copy c:\ram\gcurpos.c a:\ram\
df a:

