mkdir a:\ram
copy c:\ram\latest a:\ram\
copy c:\ram\back2.bat a:\ram\
copy c:\ram\idfield.c a:\ram\
copy c:\ram\idselbx.c a:\ram\
copy c:\ram\im700.c a:\ram\
copy c:\ram\infield.c a:\ram\
copy c:\ram\initi.c a:\ram\
copy c:\ram\instdsp.c a:\ram\
copy c:\ram\itcpos.c a:\ram\
copy c:\ram\kbobj.c a:\ram\
copy c:\ram\lcdlbls.c a:\ram\
copy c:\ram\ldfield.c a:\ram\
copy c:\ram\ldselbx.c a:\ram\
copy c:\ram\libdsp.c a:\ram\
copy c:\ram\librw.c a:\ram\
copy c:\ram\localkb.c a:\ram\
copy c:\ram\m7menu.c a:\ram\
copy c:\ram\m7ver.h a:\ram\
copy c:\ram\makeit.bat a:\ram\
copy c:\ram\mcpy.bat a:\ram\
copy c:\ram\midas.c a:\ram\
copy c:\ram\msl.c a:\ram\
copy c:\ram\msm.c a:\ram\
copy c:\ram\nedacc.c a:\ram\
copy c:\ram\pix2mid.c a:\ram\
copy c:\ram\procpfl.s a:\ram\
copy c:\ram\ptdisp.c a:\ram\
copy c:\ram\ptdkey.c a:\ram\
copy c:\ram\ptfield.c a:\ram\
copy c:\ram\ptread.c a:\ram\
copy c:\ram\ptselbx.c a:\ram\
copy c:\ram\ptwrite.c a:\ram\
copy c:\ram\puteq.c a:\ram\
copy c:\ram\ram.ldr a:\ram\
copy c:\ram\ramlink.bat a:\ram\
copy c:\ram\ramlink.ldr a:\ram\
copy c:\ram\rscript.c a:\ram\
df a:
