symlist atoi.o >fs.map
symlist atol.o >>fs.map
symlist blkrd.o >>fs.map
symlist blkwr.o >>fs.map
symlist close.o >>fs.map
symlist clusmap.o >>fs.map
symlist conin.o >>fs.map
symlist conwr.o >>fs.map
symlist dirfns.o >>fs.map
symlist dofmt.o >>fs.map
symlist fgets.o >>fs.map
symlist filesys.o >>fs.map
symlist filname.o >>fs.map
symlist flread.o >>fs.map
symlist fopen.o >>fs.map
symlist fprintf.o >>fs.map
symlist fputs.o >>fs.map
symlist fread.o >>fs.map
symlist fscanf.o >>fs.map
symlist fseek.o >>fs.map
symlist fsinit.o >>fs.map
symlist fstubs.o >>fs.map
symlist ftell.o >>fs.map
symlist fwrite.o >>fs.map
symlist getbuff.o >>fs.map
symlist getc.o >>fs.map
symlist getl.o >>fs.map
symlist getw.o >>fs.map
symlist lseek.o >>fs.map
symlist open.o >>fs.map
symlist posit.o >>fs.map
symlist printf.o >>fs.map
symlist putc.o >>fs.map
symlist putl.o >>fs.map
symlist putw.o >>fs.map
symlist read.o >>fs.map
symlist readrn.o >>fs.map
symlist rename.o >>fs.map
symlist scan.o >>fs.map
symlist setbuf.o >>fs.map
symlist sprintf.o >>fs.map
symlist ungetc.o >>fs.map
symlist unlink.o >>fs.map
symlist write.o >>fs.map
symlist writern.o >>fs.map
